import type { Metadata } from "next";
import "@styles/globals.css";
import Header from "@components/Header";
import BottomHeader from "@components/BottomHeader";
import Footer from "@components/Footer";
import { Providers } from "@redux/Provider";
// import "react-responsive-carousel/lib/styles/carousel.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont bg-gray-300">
        <Providers>
          <Header />
          <BottomHeader />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
